Поправил
CodeMasteryCraft/ToDoProject pull request #15
Opened 2024-04-16 20:18 UTC by ppolunin

Есть некоторый диссонанс у меня по поводу реализации

2024-04-17 07:48 UTC, KirillSachkov requested changes
Уже намного лучше, осталось пару исправлений

2024-04-17 07:48 UTC, KirillSachkov commented on PetProject/PetProject/Controllers/TodoController.cs
> +            if (await db.ToDos.Where(item => item.Id == rec.Id).ExecuteUpdateAsync(item =>
хорошо, только вынеси в отдельную переменную результат выражения и потом проверь её в if, так код не будет выглядить нагромождённым

2024-04-17 07:48 UTC, KirillSachkov commented on PetProject/PetProject/Controllers/TodoController.cs
> +            var item = (await db.ToDos.AsNoTracking().FirstOrDefaultAsync(item => item.Id == id, ct));
Вместе FirstOfDefault здесь лучше использовать метод FindAsync, для поиска по id. Потому что FindAsync работает производительнее, в некоторых ситуациях он берет данные из кэша

2024-04-18 07:39 UTC, ppolunin commented on PetProject/PetProject/Controllers/TodoController.cs
> +            var item = (await db.ToDos.AsNoTracking().FirstOrDefaultAsync(item => item.Id == id, ct));
В этом решении во всех методах кэширование избегается. [DbContext](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/) по умолчанию, транзиторный, живёт столько, сколько контроллер, который создаётся при каждом запросе, поэтому, в нашем простейшем случае, в кэшировании смысла нет.

2024-04-18 08:46 UTC, KirillSachkov commented
Отлично, теперь всё хорошо

2024-04-18 08:47 UTC, closed without merging